### ISSUE TITLE
Error compiling on Mac OSX High Sierra

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.recipe.varnish#57]
Maybe it goes wrong on earlier versions too, but I think it worked for me before I upgraded to High Sierra. Error:

```
File ".../plone/recipe/varnish/tests/recipe.rst", line 48, in recipe.rst
Failed example:
    'varnish' in os.listdir('bin')
Expected:
    True
Got:
    False
```

I add this in `recipe.rst` right before this line to see a more complete error, probably good to add that in the source:

```
    >>> if 'Traceback' in output:
    ...     print(output)
```

Error then becomes:

```
File "/Users/maurits/community/plone.recipe.varnish/plone/recipe/varnish/tests/recipe.rst", line 45, in recipe.rst
Failed example:
    if 'Traceback' in output:
        print(output)
Expected nothing
Got:
    Not found: /var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpIEzxYJbuildouttests/zc.recipe.cmmi/
    Not found: /var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpIEzxYJbuildouttests/zc.recipe.cmmi/
    Not found: /var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpIEzxYJbuildouttests/jinja2/
    Not found: /var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpIEzxYJbuildouttests/jinja2/
    Not found: /var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpIEzxYJbuildouttests/markupsafe/
    Not found: /var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpIEzxYJbuildouttests/markupsafe/
    Installing varnish-build.
    varnish-build: Downloading http://varnish-cache.org/_downloads/varnish-5.2.1.tgz
    varnish-build: Unpacking and configuring
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmp8tBqP8buildout-varnish-build/varnish-5.2.1':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    varnish-build: cmmi failed: /var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmp8tBqP8buildout-varnish-build
    While:
      Installing varnish-build.
    <BLANKLINE>
    An internal error occurred due to a bug in either zc.buildout or in a
    recipe being used:
    Traceback (most recent call last):
      File "/Users/maurits/community/plone.recipe.varnish/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2123, in main
        getattr(buildout, command)(args)
      File "/Users/maurits/community/plone.recipe.varnish/lib/python2.7/site-packages/zc/buildout/buildout.py", line 796, in install
        installed_files = self[part]._call(recipe.install)
      File "/Users/maurits/community/plone.recipe.varnish/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1553, in _call
        return f()
      File "/private/var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpN4zHBXbuildoutSetUp/_TEST_/sample-buildout/eggs/zc.recipe.cmmi-2.0.0-py2.7.egg/zc/recipe/cmmi/__init__.py", line 115, in install
        self.build()
      File "/private/var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpN4zHBXbuildoutSetUp/_TEST_/sample-buildout/eggs/zc.recipe.cmmi-2.0.0-py2.7.egg/zc/recipe/cmmi/__init__.py", line 197, in build
        self.cmmi(dest)
      File "/Users/maurits/community/plone.recipe.varnish/plone/recipe/varnish/recipe.py", line 118, in cmmi
        system('%s %s' % (self.configure_cmd, options))
      File "/private/var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpN4zHBXbuildoutSetUp/_TEST_/sample-buildout/eggs/zc.recipe.cmmi-2.0.0-py2.7.egg/zc/recipe/cmmi/__init__.py", line 32, in system
        subprocess.check_call(c, shell=True)
      File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command './configure --prefix="/private/var/folders/g1/3lr2tj2d1vn80qb686lcbrbm0000gp/T/tmpN4zHBXbuildoutSetUp/_TEST_/sample-buildout/parts/varnish-build"' returned non-zero exit status 77
```

That is with the varnish-5 branch from PR #56, but I see the same on master with varnish 4.

**Comment by mauritsvanrees** [comment]
Ah, duh! The important line here is:

```
configure: error: C compiler cannot create executables
```

I need to start XCode and install some stuff and run `xcode-select -r` to reset to the default path, as I changed it manually earlier for some reason. See
https://stackoverflow.com/questions/10357804/configure-error-c-compiler-cannot-create-executables

Now it works.

**Comment by cleberjsantos** [comment]
:+1:
